export const SET_WORK_TYPE = 'SET_WORK_TYPE';
export const FETCH_WORK_TYPE = 'FETCH_WORK_TYPE';

export const FETCH_LEVEL = 'FETCH_LEVEL';
export const SET_LEVEL = 'SET_LEVEL';

export const FETCH_PAPER_FORMAT = 'FETCH_PAPER_FORMAT';
export const SET_PAPER_FORMAT = 'SET_PAPER_FORMAT';